### ISSUE TITLE
Authentication Failure (cause Synch failure) to MME

### ISSUE THREAD

**Issue by vimal2828** [facebookexperimental/S1APTester#23]
### Your Environment

- **Ubuntu 18.04**
- **TestCntlrStub**
- **Affected Subcomponent:**
- **Deployment Environment:**

### Describe the Issue
I tried LTE attach using the TestCntlrStub.
S1-connection with MME was successful but NAS authentication failed with cause "21".
I used the same default configuration of ueCfg.txt file.
The MME I use it takes OPC and KEY. 

**To Reproduce**
Perform attach using this stub.

**Expected behavior**
Successful Authentication procedure

**Screenshots**

**Additional context**
If possible then please share the sample configuration (keys related) of stub side and MME side then it would be really helpful.

**Comment by vimal2828** [comment]
Able to solve it.

**Comment by crbertoldo** [comment]
> Able to solve it.

@vimal2828, please: do you remember how?

**Comment by jayshankarnair** [comment]
@vimal2828 how did u solve it.
