### ISSUE TITLE
Building TestCntrlStub failed

### ISSUE THREAD

**Issue by northmirko** [facebookexperimental/S1APTester#35]
Hello, I cant compile test scenario.
Can you help ?
../src/ts_utls.c:1769:47: error: ‘PartialReset’ {aka ‘struct _PartialReset’} has no member named ‘ueIdLst’

`vagrant@vagrant:~/S1APTester/TestCntlrStub/build$ make all
make -f tc.mak all
make[1]: Entering directory '/home/vagrant/S1APTester/TestCntlrStub/build'
Compiling ts_utls.c...
gcc -g3 -c -Wall -Werror -DUNUSED ../src/ts_utls.c -DTFW_STUB -I../../TestCntlrApp/src/tfwApp \
   -I../../Trfgen/src -o ../obj/ts_utls.o
../src/ts_utls.c: In function ‘tsSendResetReq’:
../src/ts_utls.c:1768:40: error: ‘PartialReset’ {aka ‘struct _PartialReset’} has no member named ‘ueIdLst’
 1768 |       ((ResetReq*)msgptr)->r.partialRst.ueIdLst = malloc(numOfUes);
      |                                        ^
../src/ts_utls.c:1769:47: error: ‘PartialReset’ {aka ‘struct _PartialReset’} has no member named ‘ueIdLst’
 1769 |       memcpy(((ResetReq*)msgptr)->r.partialRst.ueIdLst, ueLst, numOfUes);
      |                                               ^
../src/ts_utls.c:1772:45: error: ‘PartialReset’ {aka ‘struct _PartialReset’} has no member named ‘ueIdLst’
 1772 |       free(((ResetReq*)msgptr)->r.partialRst.ueIdLst);
      |                                             ^
make[1]: *** [tc.mak:73: ../obj/ts_utls.o] Error 1
make[1]: Leaving directory '/home/vagrant/S1APTester/TestCntlrStub/build'
make: *** [Makefile:2: all] Error 2`

**Comment by northmirko** [comment]
I made change in ts_utls.c  .


Replaced `r.partialRst.ueIdLst` with 
 `r.partialRst.ueS1apIdPairList`

**Comment by nickvsnetworking** [comment]
Hi @northmirko - The changes you suggested worked for me and allowed me to compile, so I put the [changes you suggested into a PR here,](https://github.com/facebookexperimental/S1APTester/pull/39)

**Comment by northmirko** [comment]
Thank you @nickvsnetworking .
